code = "541712"
name = "Research and Development in the Physical, Engineering, and Life Sciences (except Biotechnology)"
sic_correlations = ["3721", "3724", "3728", "8732", "3769", "3764", "3761", "8733", "8733"]